import fs from "node:fs";
import path from "node:path";
import { SHIM_DIR } from "./config.js";

/**
 * During its login / "get tokens" OAuth flow, Claude Code auto-launches the
 * system browser (via `open` on macOS) to the auth URL. Because Voyager runs
 * each session on the same machine you view it from, that launch hijacks the
 * very browser tab showing the terminal. There is no env var to disable it.
 *
 * Claude also prints the URL to the terminal, so we shadow `open` with a shim
 * that, for http(s) URLs, prints the URL (clickable via the web-links addon)
 * instead of launching a browser. Any other `open` invocation passes straight
 * through to the real `/usr/bin/open`, so file/app opening still works.
 */
const SHIM_SCRIPT = `#!/bin/sh
# Voyager browser shim — generated by server/src/browser-shim.ts.
for arg in "$@"; do
  case "$arg" in
    http://*|https://*)
      printf '\\n[voyager] Open this URL in a new browser tab:\\n  %s\\n\\n' "$arg"
      exit 0
      ;;
  esac
done
exec /usr/bin/open "$@"
`;

let ensured = false;

/**
 * Write the browser shim (idempotent) and return the dir to prepend to PATH.
 * Only meaningful on macOS, where the system opener is `open`.
 */
export function ensureBrowserShim(): string {
  if (!ensured) {
    fs.mkdirSync(SHIM_DIR, { recursive: true });
    const shimPath = path.join(SHIM_DIR, "open");
    fs.writeFileSync(shimPath, SHIM_SCRIPT, { mode: 0o755 });
    fs.chmodSync(shimPath, 0o755); // writeFileSync mode is masked by umask
    ensured = true;
  }
  return SHIM_DIR;
}
